### ISSUE TITLE
Create documentation with MDocs for Python Library

### ISSUE THREAD

**Issue by KjetilIN** [RIT-NTNU-Bachelor/OpenCV_Server#20]
IDEA: Use MDocs to create the documentation for the Python Library
https://www.mkdocs.org/getting-started/

**Comment by KjetilIN** [comment]
Using this article: https://realpython.com/python-project-documentation-with-mkdocs/#step-4-prepare-your-documentation-with-mkdocs

**Comment by KjetilIN** [comment]
Status update: 


![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/cfbb4aac-efa2-4ddd-85a3-de16f262cff4)

**Comment by KjetilIN** [comment]
# Up for review

Deployed the docs to github pages. 

Link here: https://rit-ntnu-bachelor.github.io/OpenCV_Server/

Feel free to check it out @haugeSander

**Comment by saada865** [comment]
Hey! Do you have a task that requires doing documentation?

**Comment by marhjoh** [comment]
@saada865 hello, as this is our bachelor's thesis, we emphazize documentation. However, we're to work on this without any help at the moment. You'd be able to look into it after it has been delivered in the end of May/ mid July though
